<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>DiscussWithMe - Coding Forum</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<style>
    .read-more-text{
        display: none;
    }
    .read-more-text--show{
        display: inline;
    }
</style>
<body style="background-color: #F2F3F7;">
    <?php include 'partials/dbconnect.php' ?>
    <?php include 'partials/header.php' ?>
    <!-- <?php
    $id = $_GET['catid'];
    $sql = "SELECT * FROM `categories` WHERE category_id=$id";
    $result = mysqli_query($conn, $sql);
    while ($row = mysqli_fetch_assoc($result)) {
        $catname = $row['category_name'];
        $catdesc = $row['category_description'];
    }
    ?>

    <?php
    $showAlert = false;
    $method = $_SERVER['REQUEST_METHOD'];

    if ($method == 'POST') {
        //insert thread into db
        $th_title = $_POST['title'];
        $th_desc = $_POST['desc'];

        $th_title = str_replace("<", "&lt;", $th_title);
        $comment = str_replace(">", "&gt;", $th_title);

        $th_desc = str_replace("<", "&lt;", $th_desc);
        $th_desc = str_replace(">", "&gt;", $th_desc);

        $sno = $_POST['sno'];
        $sql = "INSERT INTO `threads` (`thread_title`, `thread_desc`, `thread_cat_id`, `thread_user_id`, `timestamp`) VALUES ('$th_title', '$th_desc', '$id', '$sno', current_timestamp())";
        $result = mysqli_query($conn, $sql);
        $showAlert = true;
        if ($showAlert) {
            echo '<div class="alert alert-success alert-dismissible fade show" role="alert">
                    <strong>Success!</strong> Your thread has been added! Please wait for cummunity to respond.
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>';
        }
    }
    ?> -->

    <!-- category container -->
    <div class="container my-3 rounded" >
        <div class="card" style="border-radius: 20px; background:#C2E0EE; box-shadow: -5px -5px 9px #ffffff73, 5px 5px 7px #5e687949;">
            <div class="read-more-container card-body m-2" style="box-shadow:inset -5px -5px 9px #ffffff73,inset 5px 5px 7px #5e687949; border-radius:20px;">
                <h1 class="card-title">Welcome to <?php echo $catname; ?> forums</h1><br>
                <p class="lead fw-semibold"><?php echo $catdesc; ?></p>
                <p class=" card-text"><b>General Forum Rules</b></p>
                <ul class="container">
                    <li>Incivility towards another member or a moderator will not be tolerated, please treat all members with respect and courtesy at all times. Deliberately starting arguments and other troll behavior is forbidden.</li>
                    <li>No pornographic or nude images, No images or descriptions of bestiality, necrophilia, pedophilia, or rape. No hate speech or incitement or threats to commit illegal acts. No harassment of, or unwanted advances to, another member either on open forum or by private message.</li>
                    <li> No claiming to be an admin, moderator, or other staff member when you are not. This includes screen names or avatars implying you are a staff member, as well as any post impersonating one.</li>
                    <li>Posting spam or any other unauthorized advertising anywhere on the site will lead to an instant permanent ban. By advertising we mean the promotion of any product, service, or site that you are affiliated with, or stand to benefit from in any way. You are allowed to link to your published work in the success stories forum, and in your signature (see below).</li>
                    <span class="read-more-text">
                        <li>Market research is not allowed.</li>
                        <li>We do not allow the discussion or promotion of cracked apps, pirated software, or other forms of hacking such as techniques for compromising phones or devices.</li>
                        <li>Homework, university coursework, competition entries, and other work intended to reflect individual effort, should not be posted for critique. Our members will not do your work for you.</li>
                        <li>No thread bumping, i.e. appending meaningless posts to bring a thread to the top, or creating duplicates of threads to garner attention.</li>
                        <li>Posts must contain content by you. Posts generated by AIs and bots, posts with a naked link and no words, and posts that consist solely of memes or emoji's are not allowed.</li>
                        <li>This is a writing forum, please use writing in English to communicate. Although we don't insist on perfect grammar, a minimum standard of legibility and comprehensibility is required. Posts that don't make sense will be removed.</li>
                        <li>We do not delete, or allow the deletion of, content without good reason. Minor alterations to correct typos, or add more information, or deleting a remark you thought better of before it is replied to is acceptable, but trashing threads by removing posts is not.</li>
                    </span>
                </ul>
                <a href="#" class="read-more-btn btn btn-outline-success mx-5">Read More</a>    
            </div>
        </div>
    </div>

    <?php
    if (isset($_SESSION['login']) && $_SESSION['login'] == true) {

        echo '<div class="container">
        <h1 class="py-2">Start a Discussion</h1>
        <form action="' . $_SERVER["REQUEST_URI"] . '" method="post">
        <div class="mb-3">
        <label for="exampleInputEmail1" class="form-label">Title</label>
        <input type="text" class="form-control" id="title" name="title" style="box-shadow:inset -5px -5px 9px #ffffff73,inset 3px 3px 5px #5e687949;">
        <div id="emailHelp" class="form-text">Keep your title as short and crisp as possible.</div>
        </div>
        <input type="hidden" name="sno" value="' . $_SESSION["sno"] . '">
        <div class="mb-3">
        <label for="exampleFormControlTextarea1" class="form-label">Elaborate your concern</label>
        <textarea class="form-control" id="desc" name="desc" rows="3" style="box-shadow:inset -5px -5px 9px #ffffff73,inset 3px 3px 5px #5e687949;"></textarea>
        </div>
        
        <button type="submit" class="btn btn-success" style="box-shadow:inset -2px -2px 5px #ffffff73,inset 5px 5px 7px #5e687949;">Submit</button>
        </form>
        </div>';
    } 
    else {
        echo '<div class="container">
        <h1 class="py-2">Start a Discussion</h1>
        <p class="lead">You are not logged in. Please login to be able to start a Discussion.</p>
        </div>';
    }
    ?>


    <div class="container mb-5">
        <h1 class="py-2">Browse Questions</h1>
        <?php
        $id = $_GET['catid'];
        $sql = "SELECT * FROM `threads` WHERE thread_cat_id=$id";
        $result = mysqli_query($conn, $sql);
        $noResult = true;
        while ($row = mysqli_fetch_assoc($result)) {
            $noResult = false;
            $id = $row['thread_id'];
            $title = $row['thread_title'];
            $desc = $row['thread_desc'];
            $thread_time = $row['timestamp'];
            $thread_user_id = $row['thread_user_id'];
            $sql2 = "SELECT user_email FROM `users` WHERE sno='$thread_user_id'";
            $result2 = mysqli_query($conn, $sql2);
            $row2 = mysqli_fetch_assoc($result2);

            echo '
            <div class="d-flex my-4 p-3 rounded" style="box-shadow: -5px -5px 9px #ffff, 5px 5px 7px #5e687949;">
            <div class="flex-shrink-0">
            <img src="/DiscussWithMe/images/user_default.png" width="54px" class="mr-3" alt="...">
            </div>
            <div class="flex-grow-1 ms-3">' .
                '<h5><a class="text-dark text-decoration-none" href="thread.php?threadid='. $id .'">'. $title .'</a></h5>
            '. $desc .'</div>' . '<p class="fw-bold my-0">Asked by: '. $row2['user_email'] .' at '. $thread_time .'</p>'.'
            </div>';
        }
        // echo var_dump($noResult);
        if ($noResult) {
            echo '<div class="alert alert-primary" role="alert">
            No questions available under this category yet!
            </div>';
        }
        ?>


        <nav aria-label="...">
            <ul class="pagination">
                <li class="page-item disabled">
                    <span class="page-link">Previous</span>
                </li>
                <li class="page-item active" aria-current="page"><a class="page-link" href="#">1</a></li>
                <li class="page-item"><a class="page-link" href="#">2</a></li>
                <li class="page-item"><a class="page-link" href="#">3</a></li>
                <li class="page-item">
                    <a class="page-link" href="#">Next</a>
                </li>
            </ul>
        </nav>

    </div>

    <?php include 'partials/footer.php' ?>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
<script>
    const parentContainer = document.querySelector('.read-more-container');

    parentContainer.addEventListener('click', event=>{
        const current = event.target;

        const isReadMoreBtn = current.className.includes('read-more-btn');

        if(!isReadMoreBtn) return;

        const currentText = event.target.parentNode.querySelector('.read-more-text');
        
        currentText.classList.toggle('read-more-text--show');

        current.textContent = current.textContent.includes('Read More') ?
        "Read Less" : "Read More";
    })
</script>

<script>
    if(window.history.replaceState){
        window.history.replaceState(null, null, window.location.href);
    }
</script>
</html>